name: CI/CD

on:
  push:
    branches: ["main"]

env:
  DOCKER_IMAGE_NAME: pixelboost-ui-cicd

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Login to Docker
        env:
          DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
          DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
        run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD

      - name: Build the Docker image
        run: docker build -t ${{secrets.DOCKER_USERNAME}}/${{env.DOCKER_IMAGE_NAME}}:latest .

      - name: Push to Docker
        run: docker push ${{secrets.DOCKER_USERNAME}}/${{env.DOCKER_IMAGE_NAME}}:latest

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Pull Docker image
        run: sudo docker pull ${{secrets.DOCKER_USERNAME}}/${{env.DOCKER_IMAGE_NAME}}:latest

      - name: Ensure Docker network exists
        run: sudo docker network create pixelboost-net || true

      - name: Delete Old Container
        run: sudo docker rm -f pixelboost-ui-container || true

      - name: Run Docker Container
        run: sudo docker run -d -p 80:80 --name pixelboost-ui-container --network pixelboost-net ${{secrets.DOCKER_USERNAME}}/${{env.DOCKER_IMAGE_NAME}}:latest
